SIM?=icarus
TOPLEVEL_LANG=verilog
WORK_BASE?=..

TOPLEVEL = dut
MODULE = test_${TOPLEVEL}

XILINX_SIM_SOURCES += \
	./axi_quad_spi_1_sim_netlist.v \

EXT_VERILOG_SOURCES += \


INT_VERILOG_SOURCES += \

COCOTB_SOURCES = \
    ./dut.sv

include ./cocotb_helper.mak
